In [5]:
import numpy as np 

In [59]:
def valid(sdm,num,i,j):
    #Row Check and Column Checj
    for k in range(9):
        #row
        if sdm[i][k]==num:
            return False
        #col
        if sdm[k][j]==num:
            return False
    i=i//3
    j=j//3
    for k in range(3):
        for l in range(3):
            if sdm[k+3*i][l+j*3]==num:
                return False
    return True

In [60]:
def total_sum(sdm):
    return np.sum(sdm)

In [182]:
def solver(sdm):
    for i in range(9):
        for j in range(9):
            if sdm[i][j]==0:
                for num in range(1,10):
                    if valid(sdm,num,i,j):
                        sdm[i][j]=num
                        if total_sum(sdm)==405:
                            return sdm
                        sdm=solver(sdm)
                        if total_sum(sdm)==405:
                            return sdm
                    
                    if num==9:
                        sdm[i][j]=0
                        return sdm
                                    

In [183]:
sudoko = np.array([[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,7,9]])

In [184]:
sudoko_1 = np.zeros((9,9))

In [185]:
solved_sudoko=solver(sudoko)

In [186]:
if np.sum(np.array(solved_sudoko))==405:
    print(solved_sudoko)
else:
    print("No soln exist")

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
